version: "3.0"

services:
  # the client has two endpoints other then the web sub portion
  # /log which displays all messages received from the hub
  # /resub which throws away the old subscription and try to create a new one.
  web-sub-client:
    image: modfin/websub-client:latest
    platform: linux/amd64
    ports:
      - "9091:9090"
    environment:
      - HOSTNAME=web-sub-client
      - PORT=9090
      - HUB_URL=http://hub:9090
      - TOPIC=/a/topic

  hub:
    build:
      context: ./hub
    ports:
      - "9090:9090"
    volumes:
      - ./hub:/go/src/hub
